import React from "react";

export function FAQSection() {
  return (
    <section>
      <h2 className="mb-6 text-3xl font-bold text-gray-900 dark:text-gray-50">
        Frequently Asked Questions
      </h2>
      <div className="space-y-6">
        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Are QR codes generated by this tool free to use commercially?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Yes, absolutely! All QR codes generated by this tool are completely
            free for personal and commercial use with no restrictions. QR code
            technology is an open standard—no one owns the rights to QR codes
            themselves. You can use generated QR codes on products, marketing
            materials, websites, and anywhere else without attribution or
            payment.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Do QR codes expire or stop working?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Static QR codes (like those generated here) never expire. The
            information is encoded directly in the QR code pattern itself, so
            they'll work forever as long as the physical code remains scannable.
            However, if your QR code links to a URL, that website must remain
            active. If the website goes down or the URL changes, the QR code
            can't be updated—you'd need to generate a new one.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            What's the difference between static and dynamic QR codes?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Static QR codes (generated by this tool) permanently encode
            information directly in the pattern. They never expire, work
            offline, and can't be edited after creation. Dynamic QR codes use a
            short URL that redirects to your content, allowing you to change the
            destination without reprinting. However, dynamic codes require a
            paid service, depend on that service staying active, and need
            internet connectivity. For most use cases, static codes are
            preferable.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Can all smartphones scan QR codes?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Yes! Modern iOS devices (iOS 11+) and Android devices (Android 9+)
            have built-in QR code scanning in their default camera apps. Users
            simply open the camera, point at the QR code, and tap the
            notification that appears. Older devices may need a dedicated QR
            scanner app from the app store. QR code scanning is now universal
            and doesn't require any special apps for most users.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            How much information can a QR code store?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            QR codes can store up to 4,296 alphanumeric characters or 7,089
            numeric characters theoretically. However, practical limits are much
            lower. More data creates more complex QR codes with smaller modules,
            making them harder to scan. For best results, keep URLs under 100
            characters, text under 300 characters, and vCards concise. Use URL
            shorteners for long links to create simpler, more scannable codes.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Is my data safe using this QR code generator?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Absolutely. All QR codes are generated entirely in your browser
            using JavaScript. No data is ever sent to our servers or any third
            party. Your WiFi passwords, contact information, URLs, and all other
            data remain completely private on your device. You can even use this
            tool offline once the page loads. Your sensitive information is
            never transmitted anywhere.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Why isn't my QR code scanning properly?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Common scanning issues: (1) Insufficient contrast—ensure dark
            foreground on light background. (2) Too small—minimum 2cm for close
            scanning. (3) Poor lighting—test under adequate light. (4) Damaged
            or dirty code—ensure clean, undamaged print. (5) No quiet zone—leave
            white space around the edges. (6) Too much data—simplify content or
            use higher error correction. (7) Low-quality printing—use
            high-resolution images (minimum 300 DPI).
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Can I add a logo to my QR code?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Yes! QR codes use error correction that allows logos to cover the
            center while maintaining scannability. Keep logos under 30% of the
            QR code area and use high error correction (Q or H level). Simple,
            high-contrast logos work best. After adding a logo, always test
            scanning from expected distances to ensure reliability.
            Logo-embedded QR codes look more professional and build brand
            recognition.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Should I use PNG or SVG format?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Use PNG for digital displays, social media, websites, and standard
            printing. Use SVG for professional printing, signage, vehicle wraps,
            or when you need to scale to different sizes. SVG is vector-based
            and maintains perfect quality at any size, making it ideal for
            large-format printing. PNG is raster-based and may pixelate when
            enlarged significantly. For most use cases, PNG at 1000×1000px works
            perfectly.
          </p>
        </details>

        <details className="group rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900">
          <summary className="cursor-pointer text-lg font-semibold text-gray-900 dark:text-gray-50">
            Can I track how many people scan my QR code?
          </summary>
          <p className="mt-3 text-gray-700 dark:text-gray-300">
            Static QR codes (generated here) don't have built-in tracking.
            However, you can create trackable QR codes by linking to a URL with
            UTM parameters (Google Analytics tracking) or using a URL shortener
            with analytics (bit.ly, TinyURL). These services show click counts,
            geographic data, and timestamps. For detailed scan analytics (device
            type, time of day, etc.), you'd need a dynamic QR code service,
            though static codes with URL tracking provide sufficient data for
            most use cases.
          </p>
        </details>
      </div>
    </section>
  );
}
